# Habilita o console do banco H2 no navegador (http://localhost:8080/h2-console)
spring.h2.console.enabled=true

# Define o caminho do console H2
spring.h2.console.path=/h2-console

# Nome do banco de dados em memória
spring.datasource.url=jdbc:h2:mem:coffeedb

# Driver JDBC do H2
spring.datasource.driverClassName=org.h2.Driver

# Usuário padrão do banco
spring.datasource.username=sa

# Senha padrão (vazia)
spring.datasource.password=

# Instrui o Hibernate a criar/atualizar as tabelas do banco automaticamente baseado nas nossas entidades Java
spring.jpa.hibernate.ddl-auto=update

# Mostra no console do Terminal os comandos SQL gerados pelo Hibernate
spring.jpa.show-sql=true
